[project]
name = "readium-mcp"
version = "0.1.0"
description = ""
authors = [
    {name = "Pablo Toledo",email = "pablotoledo@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli] (>=1.6.0,<2.0.0)"
]

[project.scripts]
readium-mcp = "src.server:main"

[tool.poetry]
packages = [{ include = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
