[project]
name = "readium-mcp"
version = "0.1.0"
description = ""
authors = [
    {name = "Pablo Toledo",email = "pablotoledo@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[project.scripts]
readium-mcp = "readium_mcp.main:main"

[tool.poetry]
packages = [{include = "readium_mcp", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
